export const PRODUCTS = {
  SUPPORT: { id: 'support', label: 'Support', color: '#FF6B35' },
  SELL: { id: 'sell', label: 'Zendesk Sell', color: '#E91E8C' },
  WFM: { id: 'wfm', label: 'Workforce Management', color: '#F5A623' },
  QA: { id: 'qa', label: 'Quality Assurance', color: '#4CAF50' },
  AI_AGENTS: { id: 'ai_agents', label: 'AI Agents', color: '#5B7FFF' },
  ADMIN_CENTER: { id: 'admin_center', label: 'Admin Center', color: '#7B61FF' },
}

export const CATEGORIES = {
  CRITICAL: 'critical',
  BILLING: 'billing',
  INCIDENT: 'incident',
  FEATURE: 'feature',
  ADOPTION: 'adoption',
  SETUP: 'setup',
  MAINTENANCE: 'maintenance',
}

export const URGENCY = {
  ACTION_REQUIRED: 'action_required',
  INFORMATIONAL: 'informational',
}

export const notifications = [
  {
    id: 1,
    title: 'Zendesk Sell is being retired on August 31, 2027',
    description: 'We have partnered with Pipeline to ensure a smooth transition to their solution. Please review your migration options and begin planning your transition.',
    product: PRODUCTS.SELL,
    category: CATEGORIES.CRITICAL,
    urgency: URGENCY.ACTION_REQUIRED,
    cta: { label: 'Learn more', url: '#' },
    timestamp: '2026-06-10T09:00:00Z',
    read: false,
    dismissed: false,
  },
  {
    id: 2,
    title: 'Your bill is past due',
    description: 'Your account has an outstanding balance. Please update your payment method to avoid service interruption.',
    product: PRODUCTS.ADMIN_CENTER,
    category: CATEGORIES.BILLING,
    urgency: URGENCY.ACTION_REQUIRED,
    cta: { label: 'Update payment', url: '#' },
    timestamp: '2026-06-14T14:00:00Z',
    read: false,
    dismissed: false,
  },
  {
    id: 3,
    title: 'Your storage is 92% full',
    description: 'You are approaching your storage limit. Upgrade your plan or clean up attachments to avoid disruption to ticket handling.',
    product: PRODUCTS.ADMIN_CENTER,
    category: CATEGORIES.BILLING,
    urgency: URGENCY.ACTION_REQUIRED,
    cta: { label: 'Upgrade now', url: '#' },
    timestamp: '2026-06-12T11:30:00Z',
    read: false,
    dismissed: false,
  },
  {
    id: 4,
    title: 'Service incident — Talk service degraded',
    description: 'We are currently experiencing degraded performance with Zendesk Talk in Pod 17. Our team is actively investigating. Estimated resolution: 2 hours.',
    product: PRODUCTS.SUPPORT,
    category: CATEGORIES.INCIDENT,
    urgency: URGENCY.ACTION_REQUIRED,
    cta: { label: 'View status', url: '#' },
    timestamp: '2026-06-16T08:15:00Z',
    read: false,
    dismissed: false,
  },
  {
    id: 5,
    title: 'Scheduled maintenance — June 20',
    description: 'Routine maintenance is scheduled for June 20, 2026 from 2:00 AM to 4:00 AM UTC. You may experience brief interruptions during this window.',
    product: PRODUCTS.ADMIN_CENTER,
    category: CATEGORIES.MAINTENANCE,
    urgency: URGENCY.ACTION_REQUIRED,
    cta: { label: 'See details', url: '#' },
    timestamp: '2026-06-13T10:00:00Z',
    read: false,
    dismissed: false,
  },
  {
    id: 6,
    title: 'You have 5 unused agent licenses',
    description: 'Your account has 5 agent seats that haven\'t been assigned. Consider inviting more team members or adjusting your subscription to optimize costs.',
    product: PRODUCTS.ADMIN_CENTER,
    category: CATEGORIES.ADOPTION,
    urgency: URGENCY.INFORMATIONAL,
    cta: { label: 'Manage licenses', url: '#' },
    timestamp: '2026-06-11T09:00:00Z',
    read: false,
    dismissed: false,
  },
  {
    id: 7,
    title: 'AI Agents is now available on your plan',
    description: 'AI-powered agents can now handle common customer requests automatically. Set up your first AI agent to start deflecting tickets and reducing wait times.',
    product: PRODUCTS.AI_AGENTS,
    category: CATEGORIES.FEATURE,
    urgency: URGENCY.INFORMATIONAL,
    cta: { label: 'Get started', url: '#' },
    timestamp: '2026-06-09T13:00:00Z',
    read: false,
    dismissed: false,
  },
  {
    id: 8,
    title: 'New: Quality Assurance is live',
    description: 'Always-on quality assurance you can count on. Start reviewing agent conversations automatically with AI-powered scoring and coaching insights.',
    product: PRODUCTS.QA,
    category: CATEGORIES.FEATURE,
    urgency: URGENCY.INFORMATIONAL,
    cta: { label: 'Explore QA', url: '#' },
    timestamp: '2026-06-08T10:00:00Z',
    read: true,
    dismissed: false,
  },
  {
    id: 9,
    title: 'Finish setting up your Zendesk instance',
    description: 'You\'re almost there! Complete these remaining steps to get the most out of Zendesk: configure your email channel, set up business hours, and create your first automation.',
    product: PRODUCTS.ADMIN_CENTER,
    category: CATEGORIES.SETUP,
    urgency: URGENCY.INFORMATIONAL,
    cta: { label: 'Continue setup', url: '#' },
    timestamp: '2026-06-05T08:00:00Z',
    read: true,
    dismissed: false,
  },
  {
    id: 10,
    title: 'Your price is changing on September 1',
    description: 'As part of our annual pricing update, your plan rate will change effective September 1, 2026. Review the details and contact your account team with questions.',
    product: PRODUCTS.ADMIN_CENTER,
    category: CATEGORIES.BILLING,
    urgency: URGENCY.ACTION_REQUIRED,
    cta: { label: 'Review changes', url: '#' },
    timestamp: '2026-06-07T09:00:00Z',
    read: false,
    dismissed: false,
  },
  {
    id: 11,
    title: 'Workforce Management EAP is now GA',
    description: 'The Workforce Management early access program has graduated to general availability. All EAP features are now permanently available on your plan.',
    product: PRODUCTS.WFM,
    category: CATEGORIES.FEATURE,
    urgency: URGENCY.INFORMATIONAL,
    cta: { label: 'See what\'s new', url: '#' },
    timestamp: '2026-06-06T11:00:00Z',
    read: true,
    dismissed: false,
  },
  {
    id: 12,
    title: 'You\'re being migrated to the new messaging experience',
    description: 'Your account is scheduled for migration to our enhanced messaging platform on July 15, 2026. This includes new features like conversation continuity and rich media support.',
    product: PRODUCTS.SUPPORT,
    category: CATEGORIES.CRITICAL,
    urgency: URGENCY.ACTION_REQUIRED,
    cta: { label: 'Prepare for migration', url: '#' },
    timestamp: '2026-06-04T10:00:00Z',
    read: false,
    dismissed: false,
  },
  {
    id: 13,
    title: 'Consider switching to an annual contract',
    description: 'Your account is currently on a monthly billing cycle. Switching to annual billing saves you 15% — that\'s $2,340/year based on your current usage.',
    product: PRODUCTS.ADMIN_CENTER,
    category: CATEGORIES.ADOPTION,
    urgency: URGENCY.INFORMATIONAL,
    cta: { label: 'Compare plans', url: '#' },
    timestamp: '2026-06-03T14:00:00Z',
    read: true,
    dismissed: false,
  },
  {
    id: 14,
    title: 'Security incident — action required',
    description: 'A security vulnerability was identified in a third-party integration. We recommend rotating your API keys for the affected integration immediately.',
    product: PRODUCTS.ADMIN_CENTER,
    category: CATEGORIES.CRITICAL,
    urgency: URGENCY.ACTION_REQUIRED,
    cta: { label: 'Rotate keys', url: '#' },
    timestamp: '2026-06-15T16:00:00Z',
    read: false,
    dismissed: false,
  },
  {
    id: 15,
    title: 'End team inefficiencies with Zendesk WFM',
    description: 'Optimize your team\'s schedule, forecast demand, and track real-time adherence — all from within Zendesk.',
    product: PRODUCTS.WFM,
    category: CATEGORIES.ADOPTION,
    urgency: URGENCY.INFORMATIONAL,
    cta: { label: 'Learn more', url: '#' },
    timestamp: '2026-06-02T09:00:00Z',
    read: true,
    dismissed: false,
  },
  {
    id: 16,
    title: 'Manage your designated contacts',
    description: 'You can now self-manage designated contacts for your enhanced advocacy entitlements directly in Admin Center. No more support tickets needed.',
    product: PRODUCTS.ADMIN_CENTER,
    category: CATEGORIES.FEATURE,
    urgency: URGENCY.INFORMATIONAL,
    cta: { label: 'Manage contacts', url: '#' },
    timestamp: '2026-06-01T10:00:00Z',
    read: true,
    dismissed: false,
  },
  {
    id: 17,
    title: 'Incident resolved — Talk service restored',
    description: 'The Talk service degradation reported earlier today has been fully resolved. All services are operating normally. Root cause: network configuration issue in Pod 17.',
    product: PRODUCTS.SUPPORT,
    category: CATEGORIES.INCIDENT,
    urgency: URGENCY.INFORMATIONAL,
    cta: { label: 'View postmortem', url: '#' },
    timestamp: '2026-06-16T10:45:00Z',
    read: false,
    dismissed: false,
  },
  {
    id: 18,
    title: 'Give us your feedback on the new navigation',
    description: 'We\'d love to hear about your experience with the updated Admin Center navigation. Your feedback helps us improve.',
    product: PRODUCTS.ADMIN_CENTER,
    category: CATEGORIES.ADOPTION,
    urgency: URGENCY.INFORMATIONAL,
    cta: { label: 'Share feedback', url: '#' },
    timestamp: '2026-05-28T09:00:00Z',
    read: true,
    dismissed: false,
  },
  {
    id: 19,
    title: 'Set up custom AI agent responses',
    description: 'Your AI agents can be customized with brand-specific tone and knowledge. Configure custom responses to improve resolution quality.',
    product: PRODUCTS.AI_AGENTS,
    category: CATEGORIES.SETUP,
    urgency: URGENCY.INFORMATIONAL,
    cta: { label: 'Configure', url: '#' },
    timestamp: '2026-05-30T11:00:00Z',
    read: true,
    dismissed: false,
  },
  {
    id: 20,
    title: 'Your subscription renewal is approaching',
    description: 'Your annual subscription renews on August 1, 2026. Review your current plan and make any changes before the renewal date.',
    product: PRODUCTS.ADMIN_CENTER,
    category: CATEGORIES.BILLING,
    urgency: URGENCY.ACTION_REQUIRED,
    cta: { label: 'Review subscription', url: '#' },
    timestamp: '2026-06-15T09:00:00Z',
    read: false,
    dismissed: false,
  },
]
